webtalk_init -webtalk_dir /home/sky/Git_repos/thesisSimulations/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/ldpcdec_fixpt_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr  7 19:19:23 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "175173803_1777519444_210686443_565" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fa682d4f-3eed-4d7b-910b-9069d74d7b98" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2fa978aba957410a83e2dc745b075b77" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Antergos" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Antergos Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4014.502 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.35_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "131172_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2774692977 -regid "175173803_1777519444_210686443_565" -xml /home/sky/Git_repos/thesisSimulations/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/ldpcdec_fixpt_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sky/Git_repos/thesisSimulations/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/ldpcdec_fixpt_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sky/Git_repos/thesisSimulations/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/ldpcdec_fixpt_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
